export const getLabel = (id) => {
  return labels.it[id] || id;
};

export const labels = {
  it: {
    name: "Nome",
    surname: "Cognome",
    email: "Email",
    phone: "Telefono",
    route: "Tratta",
    dateStart: "Data Partenza",
    timeStart: "Orario Partenza",
    dateReturn: "Data Ritorno",
    timeReturn: "Orario Ritorno",
    notes: "Note",
    passengers: "Passeggeri",
    minimumPassengers: "Minimo passeggeri",
    duration: "Durata",
    addReturn: "Aggiungi Ritorno",
    messagePlaceholder: "Inserisci qui eventuali richieste speciali",
    goToPayment: "Vai al pagamento",
    payment: "Pagamento",
    back: "Indietro",
    next: "Avanti",
    selectTransferType: "Seleziona il tipo di transfer",
    collective: "Collettivo",
    individual: "Individuale",
    backHome: "Torna alla Home",
    loading: "Caricamento...",
    selectRoute: "Seleziona la tratta",
    price: "Prezzo",
    message: "Messaggio",
    flightInfoTitle: "Informazioni sul volo",
    flightInfoBody:
      "Indica il numero del volo e l'orario di partenza per facilitare il nostro servizio.",
    customerInfoTitle: "Informazioni sul cliente",
    customerInfoBody:
      "Inserisci i tuoi dati per la prenotazione e per eventuali comunicazioni.",
    paymentCompleted: "Pagamento completato con successo!",
    thankYouBooking:
      "Il pagamento è andato a buon fine, grazie per la tua prenotazione! Riceverai una conferma via email.",
    paymentError: "Pagamento non riuscito",
    paymentErrorDescription:
      "Qualcosa è andato storto con il pagamento. Riprova più tardi o contatta l'assistenza.",
    send: "Invia",
    sending: "Invio...",
    insertMessage: "Inserisci qui il tuo messaggio",
    contacts: "Contatti",
    whatsapp: "WhatsApp",
    footerTitle: "Contattaci",
    footerBody: "Per maggiori informazioni o richieste speciali, scrivici!",
    taxiInfoTitle: "Transfer Favignana",
    taxiInfoBody:
      "Navetta da aeroporto di Trapani o Palermo al porto di Trapani per Favignana.",
    shipInfoTitle: "Scopri Favignana",
    shipInfoBody:
      "Dalle acque cristalline alle incantevoli calette, dai sentieri panoramici alle tradizioni locali, scopri un angolo di paradiso che ti aspetta.",
    excursionInfoTitle: "Escursioni alle Saline di Trapani",
    excursionInfoBody:
      "Scopri le meraviglie delle Saline di Trapani con la vista mozzafiato delle isole Egadi sullo sfondo.",
    PDFMessage:
      "Il PDF con il riepilogo della prenotazione verrà scaricato automaticamente, clicca sul pulsante qui sotto se non viene scaricato",
    downloadPDF: "Clicca qui per scaricare il PDF",
    home: "Home",
    transfer: "Transfer",
    contactUs: "Contattaci",
    excursion: "Escursioni",
    bookingSummary: "Riepilogo prenotazione",
    contactUsTitle: "Contattaci per maggiori informazioni",
    contactUsDescription:
      "Se hai domande o vuoi assistenza con la prenotazione, siamo qui per aiutarti.",
    transferTitle: "Prenota il tuo transfer",
    transferBody:
      "Il nostro servizio di transfer è veloce, sicuro e affidabile, con partenza dagli aeroporti di Palermo e Trapani. Raggiungi facilmente il porto di Trapani, punto di imbarco per il traghetto che ti condurrà verso la splendida isola di Favignana",
    favignanaTitle: "Esplora Favignana",
    favignanaBody:
      "Con le sue acque cristalline, le spiagge incontaminate e il paesaggio mozzafiato, Favignana è la meta ideale per chi cerca relax, avventura e natura. Lasciati incantare dalla bellezza delle calette, immergiti nella storia e nella cultura dell’isola, e vivi un’esperienza unica che rimarrà nel cuore",
    paymentTitle: "Pagamento veloce e sicuro",
    paymentBody:
      "Effettua il tuo pagamento in modo rapido e sicuro grazie alla piattaforma PayPal. Con PayPal i tuoi dati saranno protetti da sistemi di sicurezza avanzati, garantendo una transazione senza preoccupazioni. Scegli la tranquillità di un pagamento facile e veloce in pochi clic!",
    CTAAbstract: "TRANSFER PER FAVIGNANA",
    CTATitle: "Prenota il tuo transfer",
    CTABody:
      "Raggiungi il porto di Trapani senza stress con il nostro servizio di transfer. Scegli il punto di partenza e prenota in pochi clic",
    CTAButton: "Prenota ora",
    CTAAbstract2: "ESCURSIONI SALINE DI NUBIA",
    CTATitle2: "Prenota la tua escursione",
    CTABody2:
      "Scopri le meraviglie delle Saline di Nubia, un luogo dove la natura e la cultura si incontrano, scegli un punto di partenza e prenota in pochi clic",
    CTAButton2: "Prenota ora",
    descTitle: "Transfer per Favignana",
    descBody:
      "Servizio transfer da e per gli aeroporti di Trapani e Palermo, con arrivo diretto al porto di Trapani per l'imbarco verso Favignana",
    homeMasterTitle: "Transfer da Trapani e Palermo per Favignana",
    transferMasterTitle: "Prenota il tuo Transfer",
    contactMasterTitle: "Contattaci",
    excursionMasterTitle: "Prenota la tua Escursione",
    blogMasterTitle: "Blog",
    privacyMasterTitle: "Privacy",
    transferDescription:
      "Favignana Transfer offre un servizio di bus navetta condiviso per raggiungere comodamente l’isola di Favignana.\n È la soluzione più conveniente e pratica per spostarsi dall’aeroporto di Trapani al porto, punto di partenza per le Isole Egadi, in soli 25 minuti. Il tragitto verso Trapani si snoda lungo la suggestiva strada delle saline, offrendo panorami mozzafiato.\n All’arrivo in aeroporto, il nostro autista ti aspetterà con un cartello riportante il logo dell'azienda 'MG Transfer'.\n Indicare nel campo apposito del modulo di prenotazione l'orario di atterraggio del volo, il numero del volo e se sono necessari seggiolini per bambini.\n I nostri veicoli sono regolarmente autorizzati e il servizio è garantito da taxi ufficiali o auto a noleggio con conducente. Per chi desidera un’esperienza ancora più esclusiva, mettiamo a disposizione anche vetture di lusso.\n Siamo un’azienda locale con profonda conoscenza del territorio, pronti a rispondere a ogni tua curiosità sulla provincia di Trapani. La nostra priorità è offrirti viaggi sicuri, comodi e trasparenti.\n Se possiedi un conto PayPal, puoi pagare il servizio in tre rate senza interessi. Per ulteriori dettagli, visita il sito di PayPal. Le tariffe, le promozioni e gli sconti sono soggetti a disponibilità e possono variare in base alla stagione.\n Contattaci per ricevere maggiori informazioni o per prenotare il tuo transfer!\n A bordo dei van è possibile che siano presenti altri passeggeri dato che il transfer è di tipo collettivo. \n Se prenoti la tratta andata e ritorno avrai uno sconto del 10%.\n Il servizio non è rimborsabile in caso di annullamento.",
    excursionDescription:
      "Scopri le Saline di Trapani: un viaggio tra natura, storia e magia del sale, parti da Trapani per un’esperienza indimenticabile tra le suggestive Saline di Nubia e le affascinanti Saline Mamma Caura.\nLasciati incantare da paesaggi unici, mulini a vento, specchi d’acqua rosa e montagne di sale che raccontano secoli di tradizione.\nDurante l’escursione potrai conoscere da vicino l’antica lavorazione del sale, osservare la fauna tipica delle zone umide e goderti panorami mozzafiato, soprattutto al tramonto.\nIl nostro servizio di escursioni parte comodamente da Trapani, con veicoli autorizzati e autisti esperti del territorio.\nTi accompagneremo lungo la famosa strada delle saline, rendendo ogni tratto del percorso parte integrante dell’esperienza.\nIl nostro staff sarà a disposizione per raccontarti curiosità e aneddoti legati a questo affascinante angolo di Sicilia.\n Indicare, se necessario, nel campo apposito del modulo di prenotazione l'orario di atterraggio del volo, il numero del volo e se sono necessari seggiolini per bambini.\n Siamo un’azienda locale con profonda conoscenza del territorio, pronti a rispondere a ogni tua curiosità sulla provincia di Trapani. La nostra priorità è offrirti viaggi sicuri, comodi e trasparenti.\n Se possiedi un conto PayPal, puoi pagare il servizio in tre rate senza interessi. Per ulteriori dettagli, visita il sito di PayPal.\nLe tariffe, le promozioni e gli sconti sono soggetti a disponibilità e possono variare in base alla stagione.\n Contattaci per ricevere maggiori informazioni\nIl servizio non è rimborsabile in caso di annullamento.",
    discountPolicy:
      "Se prenoti la tratta andata e ritorno avrai uno sconto del 10%",
    termsConditions: "Termini e condizioni",
    iAccept: "Accetto i",
    noNotes: "NESSUNA NOTA",
    flightNumber: "Numero volo",
    departureAirport: "Aeroporto di partenza",
    departureTime: "Orario di partenza",
    arrivalAirport: "Aeroporto di arrivo",
    arrivalTime: "Orario di arrivo",
    transferType: "Tipo transfer",
    oneWay: "Sola andata",
    roundTrip: "Andata e ritorno",
    time: "ore",
    excursionDepartureLocation: "Luogo di partenza",
    selectExcursion: "Seleziona escursione",
    selectLocation: "Seleziona partenza",
  },
  en: {
    name: "Name",
    surname: "Surname",
    email: "Email",
    phone: "Phone",
    route: "Route",
    dateStart: "Departure Date",
    timeStart: "Departure Time",
    dateReturn: "Return Date",
    timeReturn: "Return Time",
    notes: "Notes",
    passengers: "Passengers",
    duration: "Duration",
    addReturn: "Add Return",
    messagePlaceholder: "Enter any special requests here",
    goToPayment: "Go to Payment",
    back: "Back",
    backHome: "Back to Home",
    loading: "Loading...",
    selectRoute: "Select a route",
    price: "Price",
    message: "Message",
    paymentCompleted: "Payment successfully completed!",
    thankYouBooking:
      "Thank you for your booking! You will receive a confirmation email.",
    paymentError: "Payment failed",
    paymentErrorDescription:
      "Something went wrong with the payment. Please try again later or contact support.",
    send: "Send",
    sending: "Sending...",
    insertMessage: "Enter your message here",
    contacts: "Contacts",
    whatsapp: "WhatsApp",
    footerTitle: "Contact us",
    footerBody: "For more information or special requests, write to us!",
    taxiInfoTitle: "Transfer information",
    taxiInfoBody:
      "Private or shared transfer from Trapani and Palermo airports to the port for Favignana.",
    shipInfoTitle: "Ferry information",
    shipInfoBody: "Schedules and connections for ferries to Favignana.",
    home: "Home",
    transfer: "Transfer",
    contactUs: "Contact us",
    contactUsTitle: "Contact us for more information",
    contactUsDescription:
      "If you have questions or need help with your booking, we are here to assist you.",
    transferTitle: "Airport to Port Transfer",
    transferBody:
      "Fast and reliable transfer service from airports to the port for Favignana.",
    favignanaTitle: "Favignana",
    favignanaBody:
      "Discover the stunning island of Favignana and its breathtaking beaches.",
    paymentTitle: "Payment details",
    paymentBody:
      "Check your transfer details and complete the payment securely.",
    CTAAbstract: "Start your journey to Favignana",
    CTATitle: "Book your transfer",
    CTABody:
      "Reach the port without stress with our transfer service. Choose your starting point and book in a few clicks.",
    CTAButton: "Book now",
    descTitle: "Service description",
    descBody:
      "Transfer service to/from Trapani and Palermo airports, with direct arrival at the port for boarding to Favignana.",
    homeMasterTitle: "Welcome to Favignana Transfer",
    transferMasterTitle: "Book your airport-to-port transfer",
    contactMasterTitle: "Contact us for info and bookings",
    transferDescription:
      "Travel stress-free! We offer comfortable and punctual transfers from airports to the port for Favignana.",
  },
};
